# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true
command_timeout = 200

[git_status]
conflicted = "î®«"

[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red) '